-- Demo users for frontend "Demo as User" / "Demo as Admin" buttons
-- Email/password:
--   admin@example.com / password123  (role=admin)
--   user@example.com  / password123  (role=user)
--
-- NOTE: Password hashes are generated by bcrypt; update if you change password.

-- This file is intentionally left for manual seeding or future enhancement.
-- Recommended approach: run a small node script that uses bcrypt to hash
-- 'password123' and inserts the users.

